---
# APRSweb
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aprsweb
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: aprsweb
  replicas: 1
  template:
    metadata:
      labels:
        app: aprsweb
    spec:
      containers:
      - name: aprsweb
        image: dr.ccmo.me:8443/aprsweb:v23
        ports:
        - containerPort: 5000
        env:
          - name: DEBUG
            value: "more"
---
apiVersion: v1
kind: Service
metadata:
  name: aprsweb
spec:
  ports:
    - protocol: TCP 
      port: 5000
      targetPort: 5000
  selector:
    app: aprsweb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt
  generation: 5
  name: aprsweb
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: "aprsweb.svc.ccmo.me"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
         service:
            name: aprsweb
            port:
              number: 5000
  tls:
  - hosts:
    - aprsweb.svc.ccmo.me
    secretName: aprsweb-tls

